<Project>

  <!--
  <Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props"
          Condition=" Exists('$(MSBuildThisFileDirectory)../Directory.Build.props') "
  />
  -->

  <PropertyGroup Condition=" '$(CI)' == 'true' OR '$(TF_BUILD)' == 'true' ">
    <DontReferenceItself>true</DontReferenceItself>
  </PropertyGroup>

  <!-- CMD: dotnet restore -p:DontReferenceItself=true  other-options... -->
  <ItemGroup Condition=" '$(DontReferenceItself)' != 'true'
                     AND '$(MSBuildProjectFile)' != 'AnalyzerSandbox.csproj'
  ">
    <PackageReference Include="SatorImaging.MeticulousAnalyzer" Version="*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Include api comments for nuget packages -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(CI)' == 'true' OR '$(TF_BUILD)' == 'true' ">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Label="UserMacros">
    <GlobalPackageVersion>5.2.0-rc.14</GlobalPackageVersion>
    <GlobalPackageID>SatorImaging.MeticulousAnalyzer</GlobalPackageID>
    <GlobalPackageTitle>Meticulous Analyzer</GlobalPackageTitle>
    <GlobalPackageProduct>$(GlobalPackageTitle)</GlobalPackageProduct>
    <GlobalPackageOwner>Sator Imaging</GlobalPackageOwner>
    <GlobalPackageCompany>$(GlobalPackageOwner)</GlobalPackageCompany>
    <GlobalPackageCopyright>(c) 2024-2026 $(GlobalPackageOwner)</GlobalPackageCopyright>
    <GlobalPackageDescription>A Roslyn-based C# analyzer for detecting runtime bugs, unsafe patterns, common pitfalls, and maintainability issues.</GlobalPackageDescription>
    <GlobalPackageTags>MeticulousAnalyzer, Meticulous, Roslyn, C#, analyzer, runtime, bugs, unsafe, patterns, common, pitfalls, maintainability, SMA, StaticMemberAnalyzer, static, member, field, property</GlobalPackageTags>
    <GlobalPackageWebsite>https://x.com/sator_imaging</GlobalPackageWebsite>
    <GlobalPackageRepository>https://github.com/sator-imaging/MeticulousAnalyzer</GlobalPackageRepository>
    <GlobalPackageReleaseNote>https://github.com/sator-imaging/MeticulousAnalyzer</GlobalPackageReleaseNote>
    <GlobalPackageLicenseUrl>https://github.com/sator-imaging/MeticulousAnalyzer/blob/main/LICENSE.md</GlobalPackageLicenseUrl>
    <GlobalPackageLicenseSPDX>MIT</GlobalPackageLicenseSPDX>
    <GlobalPackageIconUrl>https://github.com/sator-imaging/MeticulousAnalyzer/raw/main/icon-128px.png</GlobalPackageIconUrl>
  </PropertyGroup>

  <PropertyGroup>
    <FileVersion>$([System.String]::Copy('$(GlobalPackageVersion)').Split('-')[0]).0</FileVersion>
    <AssemblyVersion>$([System.String]::Copy('$(GlobalPackageVersion)').Split('-')[0]).0</AssemblyVersion>
  </PropertyGroup>

</Project>
