// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

#:property LangVersion=latest

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;


const string HELP_USAGE = "USAGE: dotnet run -c Release  \"path/to/input.resx\"  \"path/to/output.md\"";

const string SUFFIX_TITLE = "_Title";
const string SUFFIX_MESSAGE_FORMAT = "_MessageFormat";
const string SUFFIX_MD_TITLE = "__MD_TITLE__";


/*  main  ================================================================ */

string? inputPath;
string? outputPath;

if (args.Length < 2
|| string.IsNullOrWhiteSpace((((inputPath = args[0]))))
|| string.IsNullOrWhiteSpace((((outputPath = args[1]))))
|| !inputPath.EndsWith(value: ".resx", StringComparison.OrdinalIgnoreCase)
|| !outputPath.EndsWith(value: ".md", StringComparison.OrdinalIgnoreCase)
)
{
    Console.Error.WriteLine(HELP_USAGE + Environment.NewLine);
    return 1;
}

var analyzerInfo = new Dictionary<string, (string diagnosticId, string title, string description, bool isCategory)>();

var xdoc = XDocument.Load(inputPath);
var root = xdoc.Root ?? throw new InvalidOperationException("The XML document is missing a root element.");

foreach (var node in root.Elements())
{
    if (node.Name != "data")
        continue;

    var name = node.Attribute(name: "name")?.Value
        ?? throw new NullReferenceException();

    var id = GetDiagnosticId(name);
    analyzerInfo.TryAdd(id, (id, string.Empty, string.Empty, false));

    var data = analyzerInfo[id];
    if (name.EndsWith(SUFFIX_TITLE))
    {
        data.title = node.Element(name: "value")?.Value ?? throw new NullReferenceException();
        analyzerInfo[id] = data;
    }
    else if (name.EndsWith(SUFFIX_MESSAGE_FORMAT))
    {
        data.description = node.Element(name: "value")?.Value ?? throw new NullReferenceException();
        analyzerInfo[id] = data;
    }
    //category
    else if (name.EndsWith(SUFFIX_MD_TITLE))
    {
        var title = node.Element(name: "value")?.Value ?? throw new NullReferenceException();
        var categoryId = id + "_Category";
        analyzerInfo.TryAdd(categoryId, (id, string.Empty, string.Empty, true));
        var catData = analyzerInfo[categoryId];
        catData.title = title;
        analyzerInfo[categoryId] = catData;
    }
}


// trying to find namespace
var resourceDirPath = Path.GetDirectoryName(Path.GetFullPath(inputPath))/* not null */!;
var analyzerTitle = Path.GetFileName(resourceDirPath);

var resourceScriptPath = Path.Combine(resourceDirPath, Path.GetFileNameWithoutExtension(inputPath) + ".Designer.cs");
if (File.Exists(resourceScriptPath))
{
    var regexp = new Regex(pattern: @"^namespace ([^\s]+)", RegexOptions.Compiled | RegexOptions.Multiline);
    var match = regexp.Match(File.ReadAllText(resourceScriptPath));
    if (match.Success)
    {
        analyzerTitle = match.Groups[1].Value;
    }
}


// writing markdown file
var sb = new StringBuilder();
sb.AppendLine("<!--");
sb.AppendLine("**IMPORTANT**: THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.");
sb.AppendLine("-->");
sb.AppendLine();
sb.AppendLine($"# {analyzerTitle}");
sb.AppendLine($"Auto-generated by `{Assembly.GetExecutingAssembly().FullName}`  ");
sb.AppendLine($"Resource file: `{inputPath}`  ");
sb.AppendLine($"Resource suffix: `{SUFFIX_TITLE}` `{SUFFIX_MESSAGE_FORMAT}` `{SUFFIX_MD_TITLE}`  ");

int maxTitleLength = analyzerInfo.Values.Select(static x => x.title.Length).DefaultIfEmpty(0).Max();

int lastNumber = int.MinValue;
foreach (var data in analyzerInfo.Values.OrderBy(static x => x.diagnosticId).ThenByDescending(static x => x.isCategory))
{
    var number = GetDiagnosticNumber(data.diagnosticId);

    //category!!
    if (data.isCategory)
    {
        sb.AppendLine();
        sb.AppendLine($"## {data.title}");
        if (!string.IsNullOrWhiteSpace(data.description))
        {
            sb.AppendLine();
            sb.AppendLine(data.description);
        }

        sb.AppendLine();
        sb.AppendLine($"| ID      | {"Diagnostic".PadRight(maxTitleLength)} | Description");
        sb.AppendLine($"|---------|-{"-----".PadRight(maxTitleLength, paddingChar: '-')}-|-------------");

        number--;  // to avoid inserting separator
        goto NEXT;
    }
    else if (number != lastNumber + 1)  //separator
    {
        sb.AppendLine("| | | |");
    }

    sb.AppendLine($"| {data.diagnosticId} | {data.title.PadRight(maxTitleLength)} | {data.description}");

NEXT:
    lastNumber = number;
}

var dirPath = Path.GetDirectoryName(outputPath);
if (!string.IsNullOrWhiteSpace(dirPath) && !Directory.Exists(dirPath))
    Directory.CreateDirectory(dirPath);


// Reorder <data> tags
var rootElements = root.Elements().ToArray();
var dataTags = new List<XElement>(capacity: rootElements.Length);
foreach (var candidate in rootElements)
{
    if (candidate.Name.LocalName is "data")
    {
        dataTags.Add(candidate);
        candidate.Remove();
    }
}
foreach (var dt in dataTags.OrderBy(x => x.Attribute(XName.Get("name"))?.Value))
{
    root.Add(dt);
}

File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
var xmlSettings = new System.Xml.XmlWriterSettings
{
    Indent = true,
    NewLineChars = "\n",
    Encoding = Encoding.UTF8
};
using (var writer = System.Xml.XmlWriter.Create(inputPath, xmlSettings))
{
    xdoc.Save(writer);
}

Console.WriteLine(sb.ToString());
Console.WriteLine(value: "DONE");

return 0;



/*  helper  ================================================================ */

static string GetDiagnosticId(string value)
{
    var split = value.Split(separator: '_', StringSplitOptions.RemoveEmptyEntries);
    if (split.Length < 2)
        throw new ArgumentException($"Resource key '{value}' does not match the expected 'ID_Suffix' format.", nameof(value));

    return split[0];
}

static int GetDiagnosticNumber(string value)
{
    int pos = 0;
    foreach (var c in value)
    {
        if (!char.IsNumber(c))
            pos++;
    }

    if (pos >= value.Length)
        return -1;

    return int.Parse(value.Substring(pos));
}
