// <auto-generated/>

namespace SatorImaging.MeticulousAnalyzer.Analysis {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatorImaging.MeticulousAnalyzer.Analysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string SMA0001__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0001__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA0001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0001_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0001_Title {
            get {
                return ResourceManager.GetString("SMA0001_Title", resourceCulture);
            }
        }

        internal static string SMA0002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0002_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0002_Title {
            get {
                return ResourceManager.GetString("SMA0002_Title", resourceCulture);
            }
        }

        internal static string SMA0003_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0003_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0003_Title {
            get {
                return ResourceManager.GetString("SMA0003_Title", resourceCulture);
            }
        }
        
        internal static string SMA0004_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0004_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0004_Title {
            get {
                return ResourceManager.GetString("SMA0004_Title", resourceCulture);
            }
        }

        internal static string SMA0010__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0010__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA0010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0010_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0010_Title {
            get {
                return ResourceManager.GetString("SMA0010_Title", resourceCulture);
            }
        }
        
        internal static string SMA0011_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0011_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0011_Title {
            get {
                return ResourceManager.GetString("SMA0011_Title", resourceCulture);
            }
        }
        
        internal static string SMA0012_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0012_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0012_Title {
            get {
                return ResourceManager.GetString("SMA0012_Title", resourceCulture);
            }
        }
        
        internal static string SMA0015_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0015_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0015_Title {
            get {
                return ResourceManager.GetString("SMA0015_Title", resourceCulture);
            }
        }

        internal static string SMA0020__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0020__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA0020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0020_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0020_Title {
            get {
                return ResourceManager.GetString("SMA0020_Title", resourceCulture);
            }
        }
        
        internal static string SMA0021_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0021_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0021_Title {
            get {
                return ResourceManager.GetString("SMA0021_Title", resourceCulture);
            }
        }
        
        internal static string SMA0022_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0022_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0022_Title {
            get {
                return ResourceManager.GetString("SMA0022_Title", resourceCulture);
            }
        }
        
        internal static string SMA0023_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0023_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0023_Title {
            get {
                return ResourceManager.GetString("SMA0023_Title", resourceCulture);
            }
        }
        
        internal static string SMA0024_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0024_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0024_Title {
            get {
                return ResourceManager.GetString("SMA0024_Title", resourceCulture);
            }
        }
        
        internal static string SMA0025_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0025_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0025_Title {
            get {
                return ResourceManager.GetString("SMA0025_Title", resourceCulture);
            }
        }
        
        internal static string SMA0026_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0026_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0026_Title {
            get {
                return ResourceManager.GetString("SMA0026_Title", resourceCulture);
            }
        }
        
        internal static string SMA0027_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0027_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0027_Title {
            get {
                return ResourceManager.GetString("SMA0027_Title", resourceCulture);
            }
        }
        
        internal static string SMA0028_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0028_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0028_Title {
            get {
                return ResourceManager.GetString("SMA0028_Title", resourceCulture);
            }
        }

        internal static string SMA0030__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0030__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA0030_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0030_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0030_Title {
            get {
                return ResourceManager.GetString("SMA0030_Title", resourceCulture);
            }
        }
        
        internal static string SMA0031_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0031_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0031_Title {
            get {
                return ResourceManager.GetString("SMA0031_Title", resourceCulture);
            }
        }

        internal static string SMA0032_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0032_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0032_Title {
            get {
                return ResourceManager.GetString("SMA0032_Title", resourceCulture);
            }
        }

        internal static string SMA0090_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0090_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0090_Title {
            get {
                return ResourceManager.GetString("SMA0090_Title", resourceCulture);
            }
        }

        internal static string SMA0091_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0091_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0091_Title {
            get {
                return ResourceManager.GetString("SMA0091_Title", resourceCulture);
            }
        }

        internal static string SMA0092_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0092_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0092_Title {
            get {
                return ResourceManager.GetString("SMA0092_Title", resourceCulture);
            }
        }

        internal static string SMA0093_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0093_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0093_Title {
            get {
                return ResourceManager.GetString("SMA0093_Title", resourceCulture);
            }
        }

        internal static string SMA0094_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0094_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0094_Title {
            get {
                return ResourceManager.GetString("SMA0094_Title", resourceCulture);
            }
        }

        internal static string SMA0095_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0095_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0095_Title {
            get {
                return ResourceManager.GetString("SMA0095_Title", resourceCulture);
            }
        }

        internal static string SMA0096_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0096_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0096_Title {
            get {
                return ResourceManager.GetString("SMA0096_Title", resourceCulture);
            }
        }

        internal static string SMA0097_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0097_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0097_Title {
            get {
                return ResourceManager.GetString("SMA0097_Title", resourceCulture);
            }
        }

        internal static string SMA0040__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0040__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA0040_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0040_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0040_Title {
            get {
                return ResourceManager.GetString("SMA0040_Title", resourceCulture);
            }
        }

        internal static string SMA0060__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0060__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA0060_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0060_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0060_Title {
            get {
                return ResourceManager.GetString("SMA0060_Title", resourceCulture);
            }
        }

        internal static string SMA0061_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0061_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0061_Title {
            get {
                return ResourceManager.GetString("SMA0061_Title", resourceCulture);
            }
        }

        internal static string SMA0062_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0062_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0062_Title {
            get {
                return ResourceManager.GetString("SMA0062_Title", resourceCulture);
            }
        }

        internal static string SMA0063_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0063_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0063_Title {
            get {
                return ResourceManager.GetString("SMA0063_Title", resourceCulture);
            }
        }

        internal static string SMA0064_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0064_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0064_Title {
            get {
                return ResourceManager.GetString("SMA0064_Title", resourceCulture);
            }
        }

        internal static string SMA0041_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0041_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0041_Title {
            get {
                return ResourceManager.GetString("SMA0041_Title", resourceCulture);
            }
        }

        internal static string SMA0042_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0042_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0042_Title {
            get {
                return ResourceManager.GetString("SMA0042_Title", resourceCulture);
            }
        }

        internal static string SMA0050__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0050__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA0050_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0050_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA0050_Title {
            get {
                return ResourceManager.GetString("SMA0050_Title", resourceCulture);
            }
        }
        
        internal static string SMA9000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA9000__MD_TITLE__", resourceCulture);
            }
        }
        
        internal static string SMA9000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9000_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9000_Title {
            get {
                return ResourceManager.GetString("SMA9000_Title", resourceCulture);
            }
        }
        
        internal static string SMA9001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9001_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9001_Title {
            get {
                return ResourceManager.GetString("SMA9001_Title", resourceCulture);
            }
        }
        
        internal static string SMA9002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9002_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9002_Title {
            get {
                return ResourceManager.GetString("SMA9002_Title", resourceCulture);
            }
        }
        
        internal static string SMA9010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9010_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9010_Title {
            get {
                return ResourceManager.GetString("SMA9010_Title", resourceCulture);
            }
        }
        
        internal static string SMA9015_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9015_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9015_Title {
            get {
                return ResourceManager.GetString("SMA9015_Title", resourceCulture);
            }
        }
        
        internal static string SMA9020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9020_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9020_Title {
            get {
                return ResourceManager.GetString("SMA9020_Title", resourceCulture);
            }
        }
        
        internal static string SMA9021_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9021_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9021_Title {
            get {
                return ResourceManager.GetString("SMA9021_Title", resourceCulture);
            }
        }
        
        internal static string SMA9022_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9022_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9022_Title {
            get {
                return ResourceManager.GetString("SMA9022_Title", resourceCulture);
            }
        }
        
        internal static string SMA9023_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9023_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9023_Title {
            get {
                return ResourceManager.GetString("SMA9023_Title", resourceCulture);
            }
        }
        
        internal static string SMA9100_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9100_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SMA9100_Title {
            get {
                return ResourceManager.GetString("SMA9100_Title", resourceCulture);
            }
        }

        internal static string SMA8000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA8000__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA8000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8000_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8000_Title {
            get {
                return ResourceManager.GetString("SMA8000_Title", resourceCulture);
            }
        }

        internal static string SMA0043_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0043_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0043_Title {
            get {
                return ResourceManager.GetString("SMA0043_Title", resourceCulture);
            }
        }

        internal static string SMA0044_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0044_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0044_Title {
            get {
                return ResourceManager.GetString("SMA0044_Title", resourceCulture);
            }
        }

        internal static string SMA0045_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0045_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0045_Title {
            get {
                return ResourceManager.GetString("SMA0045_Title", resourceCulture);
            }
        }

        internal static string SMA8010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8010_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8010_Title {
            get {
                return ResourceManager.GetString("SMA8010_Title", resourceCulture);
            }
        }

        internal static string SMA8011_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8011_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8011_Title {
            get {
                return ResourceManager.GetString("SMA8011_Title", resourceCulture);
            }
        }

        internal static string SMA0070__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0070__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA0070_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0070_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0070_Title {
            get {
                return ResourceManager.GetString("SMA0070_Title", resourceCulture);
            }
        }

        internal static string SMA0071_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0071_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0071_Title {
            get {
                return ResourceManager.GetString("SMA0071_Title", resourceCulture);
            }
        }

        internal static string SMA0080__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0080__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA0080_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0080_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA0080_Title {
            get {
                return ResourceManager.GetString("SMA0080_Title", resourceCulture);
            }
        }

        internal static string SMA0090__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0090__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA7000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA7000__MD_TITLE__", resourceCulture);
            }
        }

        internal static string SMA8001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8001_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7000_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7000_Title {
            get {
                return ResourceManager.GetString("SMA7000_Title", resourceCulture);
            }
        }

        internal static string SMA7001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7001_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7001_Title {
            get {
                return ResourceManager.GetString("SMA7001_Title", resourceCulture);
            }
        }

        internal static string SMA7002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7002_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7002_Title {
            get {
                return ResourceManager.GetString("SMA7002_Title", resourceCulture);
            }
        }

        internal static string SMA7020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7020_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7020_Title {
            get {
                return ResourceManager.GetString("SMA7020_Title", resourceCulture);
            }
        }

        internal static string SMA7030_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7030_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7030_Title {
            get {
                return ResourceManager.GetString("SMA7030_Title", resourceCulture);
            }
        }

        internal static string SMA7040_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7040_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7040_Title {
            get {
                return ResourceManager.GetString("SMA7040_Title", resourceCulture);
            }
        }

        internal static string SMA7010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7010_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7010_Title {
            get {
                return ResourceManager.GetString("SMA7010_Title", resourceCulture);
            }
        }

        internal static string SMA7011_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7011_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA7011_Title {
            get {
                return ResourceManager.GetString("SMA7011_Title", resourceCulture);
            }
        }

        internal static string SMA8001_Title {
            get {
                return ResourceManager.GetString("SMA8001_Title", resourceCulture);
            }
        }

        internal static string SMA8002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8002_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8002_Title {
            get {
                return ResourceManager.GetString("SMA8002_Title", resourceCulture);
            }
        }

        internal static string SMA8003_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8003_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8003_Title {
            get {
                return ResourceManager.GetString("SMA8003_Title", resourceCulture);
            }
        }

        internal static string SMA8004_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8004_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8004_Title {
            get {
                return ResourceManager.GetString("SMA8004_Title", resourceCulture);
            }
        }

        internal static string SMA8020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8020_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8020_Title {
            get {
                return ResourceManager.GetString("SMA8020_Title", resourceCulture);
            }
        }

        internal static string SMA8021_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8021_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8021_Title {
            get {
                return ResourceManager.GetString("SMA8021_Title", resourceCulture);
            }
        }

        internal static string SMA8022_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8022_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8022_Title {
            get {
                return ResourceManager.GetString("SMA8022_Title", resourceCulture);
            }
        }

        internal static string SMA8023_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8023_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8023_Title {
            get {
                return ResourceManager.GetString("SMA8023_Title", resourceCulture);
            }
        }

        internal static string SMA8030_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8030_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8030_Title {
            get {
                return ResourceManager.GetString("SMA8030_Title", resourceCulture);
            }
        }

        internal static string SMA8031_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8031_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8031_Title {
            get {
                return ResourceManager.GetString("SMA8031_Title", resourceCulture);
            }
        }

        internal static string SMA8032_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8032_MessageFormat", resourceCulture);
            }
        }

        internal static string SMA8032_Title {
            get {
                return ResourceManager.GetString("SMA8032_Title", resourceCulture);
            }
        }
    }
}
